name       : qt6-imageformats
version    : 6.2.1
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules/qtimageformats-everywhere-src-6.2.1.tar.xz : df61dc1a517988bfa123117c78a7dbeda859cbb6d9cbd080ce60058277bca3df
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt6 plugins for additional image formats
description: |
    The core Qt Gui library by default supports reading and writing image files of the most common file formats and a few more. The Qt Image Formats add-on module provides optional support for other image file formats.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(jasper)
    - pkgconfig(libjpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
rundeps    :
    - devel :
        - qt6-base-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
