name       : qt6-imageformats
version    : 6.3.0
release    : 4
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtimageformats-everywhere-src-6.3.0.tar.xz : 025d0d17ed75b42a7eb6b523731ab8f17025421a8810cade25caffe05d93abef
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt6 plugins for additional image formats
description: |
    The core Qt Gui library by default supports reading and writing image files of the most common file formats and a few more. The Qt Image Formats add-on module provides optional support for other image file formats.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(jasper)
    - pkgconfig(libjpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
rundeps    :
    - devel :
        - qt6-base-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
